Add Propagators
QEDjl-project/QEDprocesses.jl pull request #28
Opened 2023-10-18 21:29 UTC by szabo137

This PR adds a simple implementation of fermion and boson propagators. 

This should be merged *before* #18 because the latter will use the functionality.

2023-11-07 13:49 UTC, szabo137 commented
@AntonReinhard This should be ready for review now. Could you please have a look on this?

2023-11-08 14:10 UTC, AntonReinhard requested changes

2023-11-08 14:10 UTC, AntonReinhard commented on src/propagators.jl
> +propagator(particle_type::Photon, K::QEDbase.AbstractFourMomentum) = _scalar_propagator(K)
Can we make this into a whole `function ... end` too just for the niceness?

2023-11-08 14:10 UTC, AntonReinhard commented on test/propagators.jl
> +ATOL = 0.0
atol defaults to zero anyways

2023-11-12 22:21 UTC, szabo137 commented on test/propagators.jl
> +ATOL = 0.0
This was made explicitly to not rely on defaults of `isapprox`, and it is better to read.

2023-11-12 22:25 UTC, szabo137 commented on src/propagators.jl
> +propagator(particle_type::Photon, K::QEDbase.AbstractFourMomentum) = _scalar_propagator(K)
Niceness reestablished in 77c5494

2023-11-13 08:55 UTC, AntonReinhard commented on src/propagators.jl
> +propagator(particle_type::Photon, K::QEDbase.AbstractFourMomentum) = _scalar_propagator(K)
Thank you ^^

2023-11-13 08:55 UTC, AntonReinhard approved these changes

2023-11-13 08:56 UTC, merged