Refactoring of differential cross section functionality
QEDjl-project/QEDprocesses.jl pull request #38
Opened 2023-11-14 09:08 UTC by szabo137

<<< Coming soon >>>

2023-11-14 12:45 UTC, AntonReinhard reviewed
Ok so if I understand correctly, the "pipeline" is as following:

- Public safe crossdiff [-> broadcast] -> Private safe crossdiff -> Private unsafe crossdiff -> Private unsafe probability
- Public unsafe crossdiff [-> broadcast] -> Private unsafe crossdiff -> Private unsafe probability
- Public safe probability [-> broadcast] -> Private safe probability -> Private unsafe probability
- Public unsafe probability [-> broadcast] -> Private unsafe probability

I like that the broadcast happens first thing, though it also means that for all 4 implementations we need 3 extra functions. Maybe we could reduce that to 2:
- one implementation that takes both in and out_phasespace as `AbstractVecOrMat`
- one implementation that takes in_phasespace as `AbstractVecOrMat` and out as only Vec

The first one would then broadcast only over the out_phasespace.

With julia's dynamic threaded option this shouldn't be a problem with nested threaded loops. Only problem could be with broadcasting on the GPU maybe.

2023-11-14 12:45 UTC, AntonReinhard commented on src/cross_sections.jl
> +end
Didn't we want to use broadcasting for these instead of for loops? Or is that a todo for the future?

2023-11-14 12:45 UTC, AntonReinhard commented on src/cross_sections.jl
> +    out_phase_space::AbstractVector{T},
I think these should be `AbstractVecOrMat{T}` as well
```suggestion
    in_phase_space_def::AbstactPhasespaceDefinition,
    in_phase_space::AbstractVecOrMat{T},
    out_phase_space_def::AbstactPhasespaceDefinition,
    out_phase_space::AbstractVecOrMat{T},
```

2023-11-14 13:03 UTC, AntonReinhard commented
Another thought: We should probably add an `@inline` to all of the functions that just delegate by broadcast or some check.

2023-11-29 20:45 UTC, szabo137 commented on src/interfaces/process_interface.jl
> +end
Since `Base.^(x,y)` is defined in Base and not in Core, I assume it is possible. I think here it is not necessary, because `abs2` exists.

2024-02-22 15:35 UTC, steindev reviewed
As expected, only a couple of minor comments.

2024-02-22 15:35 UTC, steindev commented on test/utils/groundtruths.jl
These are the groundtruth for your specific `TestProcess` and `TestModel`. Is this implementation actually based on anything existing that is worth documenting here?
In the end, I think it is not of relevance what you do in detail here, since you use these functions also in the interface implementation. But some basic knowledge on the test case could facilitate comprehending it.

2024-02-22 15:35 UTC, steindev commented on test/cross_sections.jl
> +                    groundtruth = _groundtruth_safe_diffCS(TestProcess(), P_IN, P_OUT)
In the `_groundtruth_safe_diffCS` you return zero in case `P_IN` and `P_OUT` is not "in phasespace" (whatever this means in detail).
Can the result `diffCS` be close enough to zero that `isapprox()` yields true although it shouldn't?

2024-02-22 15:35 UTC, steindev commented on test/utils/random_momenta.jl
> +i.e. the first entry of the vector is the null momentum, but the others pass.
should be 'i.e. the first entry of the matrix is the null momentum'

2024-02-22 15:35 UTC, steindev commented on test/utils/random_momenta.jl
> +    return moms
As I see it, `moms` is a matrix of `SFourMomentum`s with N1*N2 entries. Why do you set only two entries to zero momenta instead of iterating over at least one axis and setting the respective momenta to zero momenta?

2024-02-22 16:49 UTC, szabo137 commented on src/QEDprocesses.jl
> +# export differential_cross_section, total_cross_section
Thanks, is removed in c18a394.

2024-02-22 16:51 UTC, szabo137 commented on src/cross_sections.jl
> +Return differential cross section if the given phase spaces are physical and zero, otherwise.
Thanks, this is done in c18a394. 


btw: there is a button above the comment box with a plus/minus sign, which you may use to suggest changes. Then the change is just one click from my side 😉

2024-02-22 16:52 UTC, szabo137 commented on src/interfaces/process_interface.jl
> +Furthermore, to calculate scatteing probabilities and differential cross sections, the following
One time wrong, many times copied... big thanks to my auto-completion!

Thanks for pointing this out, is fixed in c18a394.

2024-02-22 16:52 UTC, szabo137 commented on src/interfaces/process_interface.jl
> +Interface function, which returns the incident flux of the given scatteing process for a given incoming phase-space.
Thanks, fixed in c18a394.

2024-02-22 16:53 UTC, szabo137 commented on src/interfaces/process_interface.jl
> +where ``H(\\dots)`` is the constraining of the phase space, e.g. ``\\delta^{(4)}(P_t - \\sum_i p_i)``.
Tried a clarification in c18a394. Hope it's better now.

2024-02-22 16:54 UTC, szabo137 commented on src/interfaces/process_interface.jl
> +given process and model for a passed initial phase space definition and point. The elements of the `AbstractVector` representing the initial phase space
Applied the suggestion in c18a394.

2024-02-22 16:54 UTC, szabo137 commented on src/interfaces/process_interface.jl
>  check if the length of the passed initial phase spaces match number of incoming particles.
Thanks, applied the suggestion in c18a394.

2024-02-22 16:54 UTC, szabo137 commented on test/cross_sections.jl
> +    p_out_phys_invaid = _rand_momenta(RNG, N_OUTGOING + 1)
Again the auto-completion 🤦‍♂️

Fixed it in c18a394.

2024-02-22 16:55 UTC, szabo137 commented on test/utils/random_momenta.jl
> +i.e. the first entry of the vector is the null momentum, but the others pass.
Right, this is fixed in c18a394.

2024-02-22 17:08 UTC, szabo137 commented on src/cross_sections.jl
> +function _unsafe_differential_cross_section(
Understood, in 00ad5be I added comments to all types of these functions, including the probabilities.

2024-02-23 19:47 UTC, szabo137 commented on test/utils/groundtruths.jl
Indeed, this is a full but rudimentary toy example for an implementation of the scattering process interface. The functions are designed to test specific behavior expected if the interface is implemented. 
I could add some comments to the implementation and moving the `TestProcess` and `TestModel` to the `groundtruths.jl`. Maybe it would also be convenient to rename `groundtruth.jl` to something like `test_implementation.jl`. However, I was afraid, that I overengeneer this part of the tests. Whats your opinion?

2024-02-26 10:52 UTC, szabo137 commented on test/cross_sections.jl
> +                    groundtruth = _groundtruth_safe_diffCS(TestProcess(), P_IN, P_OUT)
The differential cross section must return exactly zero if `P_IN` or `P_OUT` is not in the phase space (regardless of the specific implementation of `_is_in_phasespace`). 

Regarding the question: this is covered by the current implementation of the unit test because the groundtruth returns exactly zero and `is_approx` checks against zero exactly: 

```quote
Note that x ≈ 0 (i.e., comparing to zero with the default tolerances) is equivalent to x == 0 since the default atol is 0.
```
(from the [Julia documentation](https://docs.julialang.org/en/v1/base/math/#Base.isapprox))

2024-02-26 10:55 UTC, szabo137 commented on test/cross_sections.jl
> +                    groundtruth = _groundtruth_safe_diffCS(TestProcess(), P_IN, P_OUT)
Furthermore, in 1a52ad2 I added a more complete list of test cases for differential cross section. Especially unphysical outgoing phase spaces are included now, where `_is_in_phasespace` is extended by a check for the outgoing momenta.

2024-02-26 13:52 UTC, szabo137 commented
@steindev Thanks for reviewing, I hopefully addressed all comments. Ready for revisiting!

2024-02-28 15:32 UTC, tjungni reviewed
First half of review

2024-02-29 09:03 UTC, steindev commented on src/interfaces/process_interface.jl
> +The implementation of this function for a concrete process and model must not check if the length of
Well you are right. Nothing will break. But I am fine with 'must not', as it is a convention for the 'unsafe' implementations starting with an underscore

2024-02-29 09:14 UTC, steindev commented on test/utils/groundtruths.jl
In total, the test itself is quite complex, but I understand that is not possible to do less in order to test the interface. From my point of view, adding a bit of documentation at the beginning of the file in order to explain the aim of the test and the principle idea behind its implementation is no overengineering. If the structure of the test is mentioned in the documentation as well, I also see no need to move things or rename files.

2024-02-29 09:30 UTC, steindev commented on test/cross_sections.jl
> +                    groundtruth = _groundtruth_safe_diffCS(TestProcess(), P_IN, P_OUT)
So for some `P_IN` and `P_OUT` that are not 'in the phase space', there can be the situation, where `groundtruth` is zero (since `P_IN` and `P_OUT` are not 'in the phase space') but `diffCS` is close to zero (for whatever reason), and the `isapprox()` check yields true although the test is supposed to fail?

This is a problem, isn't it? Do you understand what I mean?

2024-02-29 09:54 UTC, szabo137 commented on test/cross_sections.jl
> +                    groundtruth = _groundtruth_safe_diffCS(TestProcess(), P_IN, P_OUT)
I understand what you mean, but `isapprox(a,zero(a),atol=zero(a))` is equivalent to `a==zero(a)`. Therefore, if the `diffCS` is close to zero, but does not exactly vanishes, then `isapprox` will return false because `diffCS != zero(diffCS)`. This means the current unit test implementation covers the case you have concerns about.

example: 

```Julia
julia> a = 1e-50
1.0e-50

julia> isapprox(a,zero(a), atol=0.0)
false 
```

2024-02-29 10:08 UTC, tjungni commented on src/interfaces/process_interface.jl
> +The implementation of this function for a concrete process and model must not check if the length of
I see, good to know!

2024-03-01 09:31 UTC, szabo137 commented on test/utils/groundtruths.jl
In 4dfb3d3, I rewrote the test implementation, made a standalone module out of it, and added some documentation. Hope this is a bit easier to understand.

2024-03-01 09:31 UTC, szabo137 commented on test/utils/random_momenta.jl
> +    return moms
I hope the rewrite in 4dfb3d3 helps with that ;-)

2024-03-01 09:34 UTC, szabo137 commented on src/cross_sections.jl
> +    for i in 1:size(out_phase_space, 2)
Currently, this implementation only supports CPU execution. However, thanks to multiple dispatch, the interface can be extended later to support GPU execution, too.

2024-03-01 09:43 UTC, szabo137 commented on src/interfaces/process_interface.jl
> +    $(TYPEDSIGNATURES)
In cd67864, the dependence on `DocStringExtensions` is dropped. This solves #41.

2024-03-01 10:17 UTC, szabo137 commented on src/interfaces/process_interface.jl
> +        in_ps::AbstractVector{T}
Right, cacae8c solves that.

2024-03-01 20:01 UTC, steindev requested changes

2024-03-01 20:01 UTC, steindev commented on test/test_implementation/random_momenta.jl
> +i.e. their first entries are null momenta.
```suggestion
i.e. their last entries are momenta of the form `ones(SFourMomentum)`.
```

2024-03-01 20:05 UTC, steindev commented on test/test_implementation/random_momenta.jl
> +i.e. the first entry of the matrix is the null momentum, but the others pass.
Also, in line 67 there is 'phase' missing after 'outgoing'.

2024-03-06 08:09 UTC, szabo137 commented on test/test_implementation/random_momenta.jl
> +    moms[1, 2] = zero(SFourMomentum)
Oh, now I get it, you are right, of course, fixed it in aa3df61.

2024-03-06 08:12 UTC, szabo137 commented on test/test_implementation/random_momenta.jl
> +i.e. the first entry of the matrix is the null momentum, but the others pass.
Right, this happens if you try to fix something in the middle of the night 😆

Fixed it in aa3df61

2024-03-06 08:12 UTC, szabo137 commented on test/test_implementation/random_momenta.jl
> +i.e. their first entries are null momenta.
Fixed in aa3df61.

2024-03-06 08:12 UTC, szabo137 commented on test/test_implementation/random_momenta.jl
> +    moms[end, 2] = ones(SFourMomentum)
Same as above. Fixed in aa3df61.

2024-03-06 10:02 UTC, steindev submitted a review, later dismissed
All comments resolved. :muscle:

2024-03-06 10:03 UTC, steindev commented
@tjungni would you please approve in case all your comments are resolved?

2024-03-06 19:29 UTC, tjungni reviewed
Added some final comments.

2024-03-06 19:29 UTC, tjungni commented on test/interfaces/process_interface.jl
> +        IN_PS_unphysical = deepcopy(IN_PS)
What about `OUT_PS_UNPHYSICAL`?

2024-03-06 19:29 UTC, tjungni commented on test/interfaces/process_interface.jl
> +                @test_throws MethodError QEDprocesses._incident_flux(PROC, MODEL, in_ps)
There is no such test for `_averaging_norm`. Is this intended?

2024-03-07 09:59 UTC, szabo137 commented on test/interfaces/setup_interface.jl
> +        @suppress QEDprocesses.incoming_particles(::TestProcess) = INCOMING_PARTICLES
Here it suppresses the warnings introduced in Julia1.10, which is raised if one overwrites a function that has already an implementation. See https://github.com/JuliaIO/Suppressor.jl

2024-03-07 10:14 UTC, szabo137 commented on test/cross_sections.jl
> +    # @suppress QEDprocesses.outgoing_particles(::TestProcess) = OUTGOING_PARTICLES
Since the test implementation has processes that gets the incoming and outgoing particles via construction, this is no longer needed. Removed it in b6bcd69

2024-03-07 10:15 UTC, szabo137 commented on test/test_implementation/random_momenta.jl
> +function _rand_out_momenta_failed(rng::AbstractRNG, N)
Agree! Renamed in b6bcd69.

2024-03-07 10:16 UTC, szabo137 commented on test/test_implementation/groundtruths.jl
> +Test implementation of the phase space check. Return `false`` if either the momentum of the first incoming particle is exactly `zero(SFourMomentum)`, or if the momentum of the last outgoing momentum
Fixed in b6bcd69.

2024-03-07 10:17 UTC, szabo137 commented on test/interfaces/process_interface.jl
> +                @test_throws MethodError QEDprocesses._incident_flux(PROC, MODEL, in_ps)
Right, thanks for pointing this out; b6bcd69 adds the respective test.

2024-03-07 10:18 UTC, szabo137 commented
@tjungni I addressed all of your comments and appreciate your approval.

2024-03-07 13:12 UTC, tjungni approved these changes
Everything looks good, ready to merge!

2024-03-07 19:27 UTC, merged